name: pedra_papel_tesoura
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/default.png
    - images/pedra.png
    - images/papel.png
    - images/tesoura.png
    - images/background.png
    - images/moldura.png

  fonts:
    - family: Minecraftia
      fonts:
        - asset: assets/fonts/Minecraftia-Regular.ttf
